# This is a basic workflow to help you get started with Actions

name: First Action CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: listing files
        run: |
          echo "before checkout"
          ls -lah
      - uses: actions/checkout@v3
      - name: listing files
        run: |
          echo "after checkout"
          ls -lah
      - name: Login to Docker Hub with action
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker run tests
        run: | 
          docker build -t mrclapham/react-test -f Dockerfile.dev .
          docker run -e CI=true mrclapham/react-test npm run test -- --coverage


  # This workflow contains a single job called "build"
  build:
    needs: tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Log into Docker Hub and run Dockerfile.dev
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mrclapham/react-test -f Dockerfile.dev .
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-bench
          environment_name: Docker-react-bench-env
          existing_bucket_name: elasticbeanstalk-us-east-1-318746526342
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
    
